# config/packages/nelmio_cors.yaml
nelmio_cors:
    defaults:
        allow_origin: ['http://localhost:5173']
        allow_headers: ['Content-Type', 'Authorization', 'X-Requested-With']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        expose_headers: []
        max_age: 3600
        allow_credentials: true # Permet l'envoi de cookies
    paths:
        '^/api/': # Appliquez cette configuration aux routes API
            allow_origin: ['*'] # Remplacez par votre domaine si nécessaire
        # '^/': null